### ISSUE TITLE
unrecognized font family react native material icons

### ISSUE THREAD

**Issue by aneena-thomas** [vishaljadav24/react-native-hide-show-password-input#10]
Showing the error "unrecognized font family react native material icons"

**Comment by patrykscheffler** [comment]
They are using `react-native-vector-icons` under the hood for showing icons. Did you link this library?

`react-native link react-native-vector-icons`

**Comment by aneena-thomas** [comment]
Yes

**Comment by vishaljadav24** [comment]
This is react-native-vector-icons issue. Refer this [link](https://github.com/react-native-training/react-native-elements/issues/503 ).
