### ISSUE TITLE
Unable to remove the default "password" label

### ISSUE THREAD

**Issue by NarendraSingh88** [vishaljadav24/react-native-hide-show-password-input#12]
Hello,
 
I am Unable to remove the default "password" label. I want my placeholder to be appeared there, instead of **password** but didn't get any way to do that.

Please suggest the way to do that.

**Comment by vishaljadav24** [comment]
Use label props for change password placeholder.

**Comment by sunilkumarkm** [comment]
Goto node_modules/react-native-hide-show-password-input folder and open src/component/passwordinput.js
In render method move ...this.props after label as shown below.
<TextField
       secureTextEntry={this.state.password}
       label="Password"
       {...this.props}
/>

Then you can pass the label props from your component.

**Comment by SirPhemmiey** [comment]
You can always  modify the component here `node_modules/react-native-hide-show-password-input folder and open src/component/passwordinput.js`.

It was a simple implementation though, i uninstalled it and rewrote mine.

**Comment by vishaljadav24** [comment]
No comments on this issue so I am closing it.
