### ISSUE TITLE
how to remove underline ? 

### ISSUE THREAD

**Issue by kaiyes** [vishaljadav24/react-native-hide-show-password-input#18]
I was wondering how to remove the underline in ios ? I can change the color to transparent but that makes the label color transparent too. 
![screen shot 2018-10-02 at 8 00 43 am](https://user-images.githubusercontent.com/5293742/46325448-15ae6480-c61a-11e8-9e55-777339b0e27c.png)

**Comment by vishaljadav24** [comment]
You can use properties of [react-native-material-textfield](https://github.com/n4kz/react-native-material-textfield#properties) and [TextInput](https://facebook.github.io/react-native/docs/textinput ).
