### ISSUE TITLE
How to change the tint color?

### ISSUE THREAD

**Issue by rauleb** [vishaljadav24/react-native-hide-show-password-input#19]
I want to change the color of the input plate and underline when focus them, any idea?
<img width="345" alt="captura de pantalla 2018-10-29 a la s 16 45 26" src="https://user-images.githubusercontent.com/5591086/47676011-31b21100-db9a-11e8-9474-cba55076a03c.png">

**Comment by wodka** [comment]
just take a look at https://github.com/n4kz/react-native-material-textfield#properties

```
                    textColor={'#FFF'}
                    baseColor={'#FFF'}
                    tintColor={'#FFF'}
                    iconColor={'#FFF'}
```

**Comment by vishaljadav24** [comment]
@wodka You are right.
