### ISSUE TITLE
Naming collision upon install with npm

### ISSUE THREAD

**Issue by hpbl** [vishaljadav24/react-native-hide-show-password-input#2]
Hey, I'm really looking forward to use you project, but when I install it with npm, and then try to run `react-native start` I get several naming collisions, like the below:

> jest-haste-map: @providesModule naming collision:
>   Duplicate module name: react-native
>   Paths: .../node_modules/**react-native-hide-show-password-input**/node_modules/react-native/package.json **collides with** .../node_modules/react-native/package.json

Do you have any idea why this may be happening?

**Comment by bailih** [comment]
+1

**Comment by kamerk22** [comment]
Closing issue feel free to re-open if it's still there.
