### ISSUE TITLE
focus()  with useRef is not work ?

### ISSUE THREAD

**Issue by l3lock** [vishaljadav24/react-native-hide-show-password-input#27]
I use useRef

`const passwordRef = useRef(null)`

In email TextField, I use onSubmitEditing to call onSubmitEmail function

`const onSubmitEmail = () => passwordRef.current.focus()`

```
<TextField
  label={'email'}
  keyboardType="email-address"
  returnKeyType="next"
  blurOnSubmit={false}
  onSubmitEditing={onSubmitEmail}
  onChangeText={email => setEmail(email)}
/>
```

And my PasswordInputText

```
<PasswordInputText
  label={'password'}
  getRef={passwordRef}
  secureTextEntry={true}
  onChangeText={password => setPassword(password)}
/>
```

And error is 
```
Error: TypeError: _this.props.getRef is not a function. (In '_this.props.getRef(ref)', '_this.props.getRef' is an instance of Object)
```

**Comment by vishaljadav24** [comment]
`getRef`  is a function and you are assigning a object. That's the issue.
If you want to use reference of the input then write the code like below:
     
    let passwordRef = null;  
    
    const onSubmitEmail = () => passwordRef.current.focus()
    
    <PasswordInputText
        label={'password'}
        getRef={ref => passwordRef = ref}
        secureTextEntry={true}
        onChangeText={password => setPassword(password)}
    />

**Comment by l3lock** [comment]
I follow your advice but it still has an error

```TypeError: Cannot read property 'current' of null```

**Comment by vishaljadav24** [comment]
I have updated my answer and it's working.
