### ISSUE TITLE
RN 0.62.2

### ISSUE THREAD

**Issue by ObidosDev** [vishaljadav24/react-native-hide-show-password-input#33]
Not working with RN 0.62.2. 
https://stackoverflow.com/questions/61226530/typeerror-undefined-is-not-an-object-evaluating-reactnative-animated-text-pr

**Comment by talyuk** [comment]
You can use my fork as a temporal solution (I've updated a dependency which causes an error)
`npm install https://github.com/talyuk/react-native-hide-show-password-input.git`

**Comment by cbhaiji** [comment]
it is also not working in react native.....
