### ISSUE TITLE
how to change the icon color to lighter gray?

### ISSUE THREAD

**Issue by laksh1010** [vishaljadav24/react-native-hide-show-password-input#6]
hi thanks for this useful library. can i know how to change just the icon color not the text color into something lighter gray. i put style prop as below but it effect the text color

`<PasswordInputText
          style={{ color: styles.$placeholderTextColorDefault }}
          placeholderTextColor={placeholderTextColor}
          tintColor={tintColor}
          underlineColorAndroid={underlineColorAndroid}
          {...props}
        />`

any idea how to access icon only style ?

**Comment by vishaljadav24** [comment]
Can't access in this version. I am working on it.

**Comment by vishaljadav24** [comment]
@laksh1010 Now you can change icon color and icon size using `iconColor` and `iconSize` props. Update library and use.
