### ISSUE TITLE
Cursor goes to beginning of input on view toggle

### ISSUE THREAD

**Issue by tsvetann** [vishaljadav24/react-native-hide-show-password-input#7]
When I toggle the password view by clicking on the icon the cursor is automatically moved to the beginning of the text input.

**Comment by vishaljadav24** [comment]
It is input text behavior when state changed. I think it is not affected for hide show functionality.

**Comment by tsvetann** [comment]
@vishaljadav24 I am not saying that your nice component is breaking anything. I would like to highlight that this is not good user experience and we should think how to fix it. Thanks

**Comment by vishaljadav24** [comment]
@tsvetann You are right. I will definitely solve this when I released next version.

**Comment by vishaljadav24** [comment]
@tsvetann You are right. I will definitely solve this when I released next version.

**Comment by vishaljadav24** [comment]
@tsvetann You are right. I will definitely solve this when I released next version.

**Comment by vishaljadav24** [comment]
@tsvetann You are right. I will definitely solve this when I released next version.

**Comment by ishaanbahal** [comment]
Did you manage to find a fix for this? This seems to be an annoying issue with TextInput!

**Comment by Jimtyagi** [comment]
@ishaanbahal  it's solved in latest version.

**Comment by lucbas** [comment]
Hi all

Were you able to solve it?

Thanks! 😄
