### ISSUE TITLE
Needs to Implement focus() method

### ISSUE THREAD

**Issue by janakact** [vishaljadav24/react-native-hide-show-password-input#9]
In many cases people use password forms in login pages. So after inserting username/email it is essential to focus to password field. Therefore, it is needed to implement a `focus()` method, similar to `focus()` method in react native `TextInput` component.

**Comment by vishaljadav24** [comment]
@janakact Sorry for late reply.
Did you try TextInput props? You can use TextInput props in this component and also can use custom props of [Material Textfield](https://github.com/n4kz/react-native-material-textfield).
